### ISSUE TITLE
글 쓴 순서는 최근 글이 위로 오도록

### ISSUE THREAD

**Issue by goodjwon** [yoodongbin/make-mini-board#15]
- 글 쓴 순서는 최근 글이 위로 오도록  정리 필요
- 글 순서는 총 수량에서 1로 되도록 23 22 21 ...  3 2 1
- 자신만 보는 글 목록
- 개인글 보는 글목록 분리

**Comment by yoodongbin** [comment]
처음에 에러가 나, 페이지가 뜨지 않아서 에러를 확인해보니 mapper 파일에서 에러가 나길래 그 부분을 어떻게 해보려고 구글링 및 이것 저것 삭제 주석처리를 하다가 주석처리 후에 보니 mysql에러더라구요 !... 디비가 연동이 되질 않아,,, 너무 너무 보기 싫었지만 !! 여차저차 해결하고 그래서 왜 잘 됐었다가 안 됐었는지에 초점을 잡아서 하느라 계속 여러가지 도전을 해보다가
결국
mysql 삭제 - > 재설치를 오가며 

하나 하나 오픈된 이슈를 수행중에 있습니다 ! 

제가 아무것도 안 하신다고 생각하실까봐 ㅠㅠ 너무나도 걱정스러웠어욥 ㅜㅡㅡㅜ

그간 주말과 재택동안 했던 공부들 정리하여 노션에 정리중에 있는데 오늘 밤엔 공유멤버로 추가하겠습니다 !

재택동안 개발자 기본 인강을 들었는데 그걸 들으며 파트장님이 저를 볼 때 얼마나 한숨이 나오셨을까 하며 감사드리고 죄송했답니다.. !!!!

 good아닌 god ! 이신 @goodjwon 파트장님 수요일날 뵙겠습니다 ! 감사합니다.

**Comment by goodjwon** [comment]
부족함을 느끼고 노력하는 모습을 유지 하는게 중요 해요.. 노력하는 것에 비하면 지금 더 알고 덜 알고는 생각보다 큰 차이가 아닐수 있어요.. 꾸준 하게 하다 보면 알게 되는 순간들이 오더라구요~  그리고 에러는 가급적 구체적으로 로그 혹은 에러메세지 혹은 화면 캡쳐 등을 남겨 놓는게 좋습니다. 예상컨테 mysql 오류가 아닐 수도 있지 않을까.. 생각이 드는데요.. 아무리 PC에 설치 했지만 엄연히 DBMS라 관련 파일을 일부러 지우거나 한게 아니면 갑작히 오류가 나는 일은 드물긴 해요. 그럼 수고요~!

**Comment by yoodongbin** [comment]
글 순서는 총 수량에서 1로 되도록 23 22 21 ... 3 2 1 - 이슈 해결하여 커밋했습니다 확인해주세요 !

**Comment by yoodongbin** [comment]
,,실수로 master에다가 바로 push했어요 ! 죄송합니다
