### ISSUE TITLE
페이징 쿼리 변경

### ISSUE THREAD

**Issue by goodjwon** [yoodongbin/make-mini-board#6]
select * from (
        select @rownum:=@rownum+1 as rn, boards.* from (

        select *, @ROWNUM:=0 from boards

        )boards
        )boards where rn between 1 and 3
;
 로 떨어지는데 일반적으로 mysql 에서는 limit를 사용 합니다.

dynamic, include 등 여러가지 기법이 있는데 순수 쿼리를 넣는게 유지보수에는 재일 좋으니 조정 바랍니다.

**Comment by yoodongbin** [comment]
넵 !
